name: UI Automation Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd 'Data File/review'
          npm install

      - name: Start Live Server
        run: npx live-server --port=8080 --entry-file=Data%20File/review/mp_events.html

      - name: Wait for server to start
        run: sleep 5

      - name: Run tests
        run: node Data%20File/review/test.js
